"""Generate ai_farm_manager_config.xml for the FS25 Lua mod (no hand-editing)."""
from __future__ import annotations

import re
from typing import Any


def _xml_escape_text(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def normalize_public_base_url(url: str) -> str:
    u = (url or "").strip().rstrip("/")
    if not u:
        return ""
    if not re.match(r"^https?://", u, re.I):
        u = "http://" + u
    return u


def resolve_backend_url_for_xml(settings: dict[str, Any], request_base_url: str | None) -> str:
    """Prefer PUBLIC_BASE_URL from .env, else reverse-proxy URL from incoming request."""
    pub = normalize_public_base_url(settings.get("public_base_url") or "")
    if pub:
        return pub
    if request_base_url:
        return str(request_base_url).rstrip("/")
    return "http://127.0.0.1:8080"


def build_mod_config_xml(
    backend_url: str,
    server_token: str,
    trigger_prefix: str,
) -> str:
    bu = _xml_escape_text(backend_url.strip())
    tok = _xml_escape_text(server_token)
    tp = _xml_escape_text((trigger_prefix or "!hank").strip())
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by AI Farm Manager — do not edit by hand; re-download from /admin if settings change. -->
<aiFarmManager>
    <backendUrl>{bu}</backendUrl>
    <serverToken>{tok}</serverToken>
    <triggerPrefix>{tp}</triggerPrefix>
    <debugChat>false</debugChat>
</aiFarmManager>
"""
